### ISSUE TITLE
Multiple links in same line are not rewritten

### ISSUE THREAD

**Issue by ralfstx** [benbalter/jekyll-relative-links#22]
I have a markdown document with the following line:

```
The current parent of a widget is returned by the [`parent`](api/Widget.md#parent) method, and the children by the [`children`](api/Widget.md#children) method.
```
The first link is correctly rewritten to `api/Widget.html#parent`, but the second link is not.

When I add a linebreak between the two links, the second one is also rewritten. Looks like some regex is missing the global flag?

**Comment by benbalter** [comment]
@dato could this be related to https://github.com/benbalter/jekyll-relative-links/pull/18?

**Comment by dato** [comment]
This bug is the same bug as #16, and is _precisely_ what #18 fixes.

But a version with this fix has not been released yet.

I assume @ralfstx is not using an unreleased version, so this issue should not happen in master. Is this something you would be able to test, @ralfstx?

I’m pretty sure anyway; the posted snippet is exactly as [this test](https://github.com/benbalter/jekyll-relative-links/commit/6a4cc8269a57904acdbc799115519669f585ba04#diff-53b04bf3ed246909a8a3ee9aac2610ea).

**Comment by ralfstx** [comment]
@dato I'm foreign to ruby, so it would be difficult for me to test an unreleased version. However, looking at the test you referred to, I'm very confident that this fix resolves exactly the kind of issue I've described. Thanks.
